### ISSUE TITLE
Incompatible change in binary-compatibility-validator since 0.10.0

### ISSUE THREAD

**Issue by qwwdfsad** [arkivanov/gradle-setup-plugin#1]
Hi,

Since 0.10.0 task `ApiCompareCompareTask` that you are relying on was renamed to `KotlinApiCompareTask`

**Comment by arkivanov** [comment]
Thanks for raising! I will fix it.

**Comment by arkivanov** [comment]
Updated the plugin to `0.10.0` in https://github.com/arkivanov/gradle-setup-plugin/commit/715d466a74bcf747b94ce9d7051228c5d1defb08
