### ISSUE TITLE
Too many artifacts published

### ISSUE THREAD

**Issue by herrbert74** [arkivanov/gradle-setup-plugin#2]
I'm using MVIKotlin and Decompose for Android only and noticed that for every library, there is an :library, a library-android-debug and a library-android-release library is published.
I noticed this while using the dependency-analysis plugin from [here](https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin).
So for example for decompose I use

`implementation("com.arkivanov.decompose:decompose:1.0.0")`

But the above plugin recommends to replace that with
```
debugImplementation("com.arkivanov.decompose:decompose-android-debug:1.0.0")
releaseImplementation("com.arkivanov.decompose:decompose-android-release:1.0.0")
```

The report is flooded with these for all of my modules, for all the MVIKotlin, Decompose, but even Essenty libraries.

The debug and release versions are only necessary if your library has different implementation for release, for example if your release is no-op. I'm not sure about Android specific versions, but as I can use the non Android ones, I think we don't need them either.

I'm not an expert in maven publishing, but I think the issue is in SetupPublication.kt, in the setupPublicationAndroidLibrary function. This can be probably replaced by a kotlin library publication (?), with the release and debug versions removed.

**Comment by arkivanov** [comment]
Glad you are using the libraries!

Indeed, this could be optimized. Currently Decompose, MVIKotlin and Essenty do not distinguish between debug and release Android variants. So we could publish just release variant. Let's keep this issue open as a reminder.

However, a library may require publishing separate variants, and so there seems to be an issue with `dependency-analysis` plugin. The proposed replacement looks verbose and basically equivalent to the shorter one, so it makes no sense to me. Maybe there is a way to configure the plugin, e.g. disable the check or something like that.

**Comment by arkivanov** [comment]
Also, we could avoid generating BuildConfig classes, they are unused.

**Comment by herrbert74** [comment]
Just a clarification, there is nothing wrong with the dependency-analysis plugin. It doesn't analyse the content of the dependencies, so it cannot tell if the debug/release versions are equivalent. However, the existence of them suggests, that it is more efficient to use them instead of the common artifact. So it should always suggest them.
Configuration and exclusion is possible, however my understanding is that this requires the plugin to be applied always, which I don't need. I use the plugin monthly-bimonthly. So I had to comment out the configuration, which is a huge list anyway, and uncomment it for every use.
